SET(CCTAG_BUILD_TYPE "Release")
# SET(CCTAG_BUILD_TYPE "Debug")

STRING( TOUPPER "${CCTAG_BUILD_TYPE}" CCTAG_BUILD_MODE )

IF(DEFINED CCTAG_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE ${CCTAG_BUILD_TYPE})
ELSE(DEFINED CCTAG_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE Debug)
ENDIF(DEFINED CCTAG_BUILD_TYPE)

set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG}   -DTHIS_IS_DEBUG_MODE")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DTHIS_IS_RELEASE_MODE")

SET(COMPILE_STATIC_CCTAG_LIBRARY true)
SET(CCTAG_SERIALIZE 0)

set(USE_CUDA true)

# add_definitions("-DCCTAG_EXTRA_LAYER_DEBUG")

