#pragma once

#define DEBUG_WRITE_ORIGINAL_AS_PGM
#define DEBUG_WRITE_ORIGINAL_AS_ASCII
#define DEBUG_WRITE_DX_AS_PGM
#define DEBUG_WRITE_DX_AS_ASCII
#define DEBUG_WRITE_DY_AS_PGM
#define DEBUG_WRITE_DY_AS_ASCII
#define DEBUG_WRITE_MAG_AS_PGM
#define DEBUG_WRITE_MAG_AS_ASCII
#define DEBUG_WRITE_MAP_AS_PGM
#define DEBUG_WRITE_MAP_AS_ASCII
#define DEBUG_WRITE_HYSTEDGES_AS_PGM
#define DEBUG_WRITE_EDGES_AS_PGM
#define DEBUG_WRITE_EDGELIST_AS_PPM
#define DEBUG_WRITE_EDGELIST_AS_ASCII
#define DEBUG_WRITE_VOTERS_AS_PPM
#define DEBUG_WRITE_CHOSEN_AS_PPM
#define DEBUG_WRITE_CHOSEN_VOTERS_AS_ASCII
#define DEBUG_WRITE_CHOSEN_ELECTED_AS_ASCII
#define DEBUG_WRITE_LINKED_AS_PPM
#define DEBUG_WRITE_LINKED_AS_PPM_INTENSE
#define DEBUG_WRITE_LINKED_AS_ASCII
#define DEBUG_WRITE_LINKED_AS_ASCII_INTENSE

#define DEBUG_LINKED_USE_INT4_BUFFER

/* Separable compilation allows one kernel to instantiate
 * others. That avoids complexity on the host side when,
 * e.g., GPU-side counters need to be checked before starting
 * a new kernel.
 */
#define USE_SEPARABLE_COMPILATION
#define USE_SEPARABLE_COMPILATION_IN_GRADDESC

